### ISSUE TITLE
[i18n]: Từ serial dịch chưa đồng nhất

### ISSUE THREAD

**Issue by hantt05** [Viindoo/odoo#153]
1. Hiện tại phần mềm dịch từ *serial* chưa đồng nhất. Chỗ là serial, chố là sê-ri, chỗ là seri.
Expect: 
- Tiếng anh: serial
- Dịch đồng nhất lại serial > sê-ri.
2. Từ *Truy suất* đang bị sai chính tả.
- Expect: *truy suất*  > *truy xuất*

![serial](https://user-images.githubusercontent.com/45425212/153325034-3b1e554e-3390-4842-917c-88268641f4d7.png)
![truyxuat](https://user-images.githubusercontent.com/45425212/153330018-67df5d63-8d22-46cc-93f6-a24e8482d931.png)

@royleviindoo anh Thông ơi assign cho ai fix giúp em phần này với nhé
cc @jennie-pham

**Comment by royle-vietnam** [comment]
@sang250399 chú làm PR dịch giúp anh cho 14.0 nhé, kiểm tra cả `odoo`, `tvtmaaddons`, `erponline-enterprise` nhé

**Comment by sang250399** [comment]
@royleviindoo dạ vâng ạ

**Comment by sang250399** [comment]
@hantt05 dịch lại hết là se-ri hay sê-ri ạ

**Comment by hantt05** [comment]
> @hantt05 dịch lại hết là se-ri hay sê-ri ạ

sê-ri em ạ. 
@sang250399

**Comment by sang250399** [comment]
@hantt05 issue này đã được xử lý. em xin phép đóng issue nhé
