### ISSUE TITLE
[15.0] Kiểm tra xem admin của module account có tạo được bank acount không

### ISSUE THREAD

**Issue by davidtranhp** [Viindoo/odoo#217]
Mãi mà thằng Odoo nó ko chịu merge thì ta tự xử vậy
@hieu1211 kiểm tra luôn giúp anh xem Odoo 15 có bị không nhé. Nếu bị thì cherry-pick cái commit này sang 15 rồi làm PR em nhé.

_Originally posted by @davidtranhp in https://github.com/Viindoo/odoo/issues/207#issuecomment-1076205197_

**Comment by hieu1211** [comment]
vâng a
