### ISSUE TITLE
@duong77476 xử ở 15 hộ anh nhé. Ở 15 thì chỗ này nó lại khác một chút.

### ISSUE THREAD

**Issue by davidtranhp** [Viindoo/odoo#413]
@duong77476 xử ở 15 hộ anh nhé. Ở 15 thì chỗ này nó lại khác một chút.

_Originally posted by @davidtranhp in https://github.com/Viindoo/odoo/issues/400#issuecomment-1191152697_

**Comment by daiduongnguyen-odoo** [comment]
> @duong77476 xử ở 15 hộ anh nhé. Ở 15 thì chỗ này nó lại khác một chút.
> 
> _Originally posted by @davidtranhp in [#400 (comment)](https://github.com/Viindoo/odoo/pull/400#issuecomment-1191152697)_

Dạ vâng ạ, cc @royleviindoo
