### ISSUE TITLE
[BUG] to_hr_payroll - sai logic người phụ thuộc

### ISSUE THREAD

**Issue by liennguyenhp** [Viindoo/odoo#63]
Impacted versions: V13

Steps to reproduce:
![Selection_028](https://user-images.githubusercontent.com/11253052/91417707-66b54a80-e87b-11ea-9f20-159dd66bfbbf.png)

Current behavior:
Hiện tại các tiêu chí thông tin người phụ thuộc trên hồ sơ nhân viên gồm:

1. Số lượng con:
2. Số lượng người phụ thuộc khác
3. Tổng số người phụ thuộc = 1 + 2

Như vậy thiếu logic vì số lượng con có thể không được cộng vào tổng số người phụ thuộc.

Expected behavior:
Để trường Tổng số người phụ thuộc cho người dùng tự điền. Trường hợp có 2 con nhưng không con nào là người phụ thuộc thì vấn có thể sử dụng trưởng tổng để tính toán thuế thu nhập cá nhân.

**Comment by davidtranhp** [comment]
Số lượng con nằm trong nhóm Người phụ thuộc nên người dùng chỉ nên nhập số lượng con mà phụ thuộc.
